# Generated by Django 5.1 on 2024-08-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='books/')),
                ('book_name', models.CharField(blank=True, max_length=250, null=True)),
                ('b_description', models.CharField(blank=True, max_length=255, null=True)),
                ('b_cost', models.ImageField(blank=True, null=True, upload_to='')),
                ('b_year_publish', models.ImageField(blank=True, null=True, upload_to='')),
                ('b_visibility', models.BigIntegerField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
